<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJIBORp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJIBORp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOJIBORp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOJIBORp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOJIBORp\App_KernelDevDebugContainer([
    'container.build_hash' => 'OJIBORp',
    'container.build_id' => 'fa5c9a91',
    'container.build_time' => 1727338585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJIBORp');
