<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHLV8I2e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHLV8I2e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHLV8I2e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHLV8I2e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHLV8I2e\App_KernelDevDebugContainer([
    'container.build_hash' => 'HLV8I2e',
    'container.build_id' => 'f5df0d95',
    'container.build_time' => 1727682716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHLV8I2e');
