<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPbmRxBx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPbmRxBx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPbmRxBx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPbmRxBx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPbmRxBx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PbmRxBx',
    'container.build_id' => '09cf46e0',
    'container.build_time' => 1727167147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPbmRxBx');
