<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ZMO4qw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ZMO4qw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8ZMO4qw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8ZMO4qw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8ZMO4qw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8ZMO4qw',
    'container.build_id' => 'e5bb5b91',
    'container.build_time' => 1727165403,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ZMO4qw');
